### ISSUE TITLE
Generated css for filter fails in chrome

### ISSUE THREAD

**Issue by romainmenke** [mrhenry/gulp-starter#5]
Chrome doesn't allow cross origin filter thingy. 

Source :
```css
.bg-img {
	.yellow {
		filter: contrast(150%) grayscale(100%);
	}
}
```

Generated :

```css
.bg-img {
  filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feComponentTransfer color-interpolation-filters="sRGB"><feFuncR type="linear" slope="1.5" intercept="-0.25" /><feFuncG type="linear" slope="1.5" intercept="-0.25" /><feFuncB type="linear" slope="1.5" intercept="-0.25" /></feComponentTransfer><feColorMatrix type="matrix" color-interpolation-filters="sRGB" values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0" /></filter></svg>#filter');
}

.bg-img .yellow {
		filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feComponentTransfer color-interpolation-filters="sRGB"><feFuncR type="linear" slope="1.5" intercept="-0.25" /><feFuncG type="linear" slope="1.5" intercept="-0.25" /><feFuncB type="linear" slope="1.5" intercept="-0.25" /></feComponentTransfer><feColorMatrix type="matrix" color-interpolation-filters="sRGB" values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0" /></filter></svg>#filter');
		-webkit-filter: contrast(150%) grayscale(100%);
		        filter: contrast(150%) grayscale(100%);
	}
```

Expected :

```css
.bg-img {
}

.bg-img .yellow {
		filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feComponentTransfer color-interpolation-filters="sRGB"><feFuncR type="linear" slope="1.5" intercept="-0.25" /><feFuncG type="linear" slope="1.5" intercept="-0.25" /><feFuncB type="linear" slope="1.5" intercept="-0.25" /></feComponentTransfer><feColorMatrix type="matrix" color-interpolation-filters="sRGB" values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0" /></filter></svg>#filter');
		-webkit-filter: contrast(150%) grayscale(100%);
		        filter: contrast(150%) grayscale(100%);
	}
```

Is there any way to modify how this is generated? Do we need to update a dependency?

**Comment by pieterbeulque** [comment]
Chrome should use the 

```
filter: contrast(150%) grayscale(100%);
```

and not nag about the generated data URI…

Does it work & throw a warning or does it not work at all? Live example?

**Comment by romainmenke** [comment]
First I thought the issue was the order, and chrome, but on closer look it is just bad code generation. It should not apply `filter: url( ....` to the parent or am I confused about how all this works?

**Comment by pieterbeulque** [comment]
This is a bug with Autoprefixer applying the SVG filter on the parent selector too. Probably a combination of Autoprefixer & the PostCSS nested plugin we use. Needs to be overridden by adding a `filter: none !important` to the parent.

```css
.selector {
  filter: none !important;

  .selector__child {
    filter: invert(100%);
  }
}
```
